version: "3.4"

services:
  envoy:
    image: envoyproxy/envoy:v1.14.1
    ports:
      - 8000:80
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  api_v1:
    image: juliocesarmidia/http-simple-api:v1.0.0
    ports:
      - 9001:9000
    environment:
      API_PORT: 9000
      MESSAGE: "api_v1"

  api_v2:
    image: juliocesarmidia/http-simple-api:v1.0.0
    ports:
      - 9002:9000
    environment:
      API_PORT: 9000
      MESSAGE: "api_v2"
