version: '3.4'

services:
  haproxy:
    image: haproxy:2.0
    ports:
      - 8000:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  api_v1:
    image: juliocesarmidia/http-simple-api:v1.0.0
    ports:
      - 9001:9000
    environment:
      API_PORT: 9000
      MESSAGE: "api_v1"

  api_v2:
    image: juliocesarmidia/http-simple-api:v1.0.0
    ports:
      - 9002:9000
    environment:
      API_PORT: 9000
      MESSAGE: "api_v2"
