version: "3.4"

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api_v1:
    image: juliocesarmidia/http-simple-api:v1.0.0
    ports:
      - 9001:9000
    environment:
      API_PORT: 9000
      MESSAGE: "api_v1"

  api_v2:
    image: juliocesarmidia/http-simple-api:v1.0.0
    ports:
      - 9002:9000
    environment:
      API_PORT: 9000
      MESSAGE: "api_v2"
